### ISSUE TITLE
10.9.2

### ISSUE THREAD

**Issue by keith** [binchewer/power_fixer#9]
It looks like yesterday's update to Mavericks broke power_fixer. Is anyone else seeing this?

**Comment by pkamb** [comment]
From @binchewer's original power_fixer:   

```
[ERROR] No timer setup. Patched already? (find_patch_place, 370)
All done.
```

From @stino's pull request branch #8:  

```
[ERROR] No call sub_10003dcb5. Patched already? (find_patch_place2, 435)
All done.
```

Yes, looks like this was broken by 10.9.2 :/

**Comment by spariev** [comment]
same here :/

```
[ERROR] No call sub_10003dcb5. Patched already? (find_patch_place2, 435)
All done.
```

**Comment by pirate** [comment]
Any way to fix this?  It's also not working for me on 10.9.2.

```
power_fixer v0.1, by binchewer
------------------------------

Found loginwindow with PID 94
loginwindow base_address is 0x000000010555b000
loginwindow text section found at offset 0x55c0, 387884 bytes
[ERROR] No timer setup. Patched already? (find_patch_place, 370)
All done.
```

**Comment by pkamb** [comment]
@nikisweeting Power_fixer isn't needed any more; Apple made the behavior configurable in OS X 10.9.2:

```
defaults write com.apple.loginwindow PowerButtonSleepsSystem -bool NO
```

I've just released [PowerKey v1.2](https://github.com/pkamb/PowerKey/releases/tag/v1.2), which includes [a link to the additional steps for 10.9 users](https://github.com/pkamb/PowerKey#additional-steps-for-os-x-109-mavericks).

**Comment by keith** [comment]
![](http://who-is-awesome.com/who-is-awesome.jpg)

**Comment by pirate** [comment]
No, You're awesome! Thanks for developing and maintaining this!
